# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('profile', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('streak', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('lingots', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
