# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0002_auto_20171120_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdata',
            new_name='User',
        ),
    ]
